@url = http://localhost:5000/conferences-module
@hostId = 0d5cb9e6-146b-419f-bdab-6edcdd6a071c

@conferenceId = fc24a835-f022-48fe-9eaf-6f71a9e47cec

###
GET {{url}}



###
GET {{url}}/hosts

###
GET {{url}}/hosts/{{hostId}}

###
POST {{url}}/hosts
Content-Type: application/json

{
    "name": "Host 2",
    "description": "Description of the Host 1"
}

###
PUT {{url}}/hosts/{{hostId}}
Content-Type: application/json

{
    "name": "Host 1 Upd",
    "description": "Description of the Host 1 Upd"
}

###
DELETE {{url}}/hosts/{{hostId}}



###
GET {{url}}/conferences

###
GET {{url}}/conferences/{{conferenceId}}

###
POST {{url}}/conferences
Content-Type: application/json

{
    "hostId": "{{hostId}}",
    "name": "Conference 4",
    "description": "Conference of the Host 1",
    "location": "Test street 123",
    "from": "2023-05-01",
    "to": "2023-05-03",
    "participantsLimit": 100
}

###
PUT {{url}}/conferences/{{conferenceId}}
Content-Type: application/json

{
    "hostId": "{{hostId}}",
    "name": "Conference 1 Upd",
    "description": "Conference of the Host 1 Upd",
    "location": "Test street 123 Upd",
    "from": "2023-10-01",
    "to": "2023-10-03"
}

###
DELETE {{url}}/conferences/{{conferenceId}}